name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Use the private key stored in GitHub Secrets
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H 16.170.95.1 >> ~/.ssh/known_hosts  # Replace with your EC2 instance's public IP

      - name: Check SSH connection to EC2
        run: |
          ssh -v -i ~/.ssh/id_rsa ec2-user@16.170.95.1 "echo 'SSH connection successful!'"

      - name: Set permissions on /var/www/html (if necessary)
        run: |
          ssh -v -i ~/.ssh/id_rsa ec2-user@16.170.95.1 << 'EOF'
            sudo chown -R ec2-user:ec2-user /var/www/html
            sudo chmod -R 755 /var/www/html
            echo "Permissions set successfully!"
          EOF

      - name: Deploy Code to EC2
        run: |
          ssh -v -i ~/.ssh/id_rsa ec2-user@16.170.95.1 << 'EOF'
            cd /var/www/html  # Navigate to the web directory
            git pull origin main  # Pull the latest code from GitHub
            echo "Deployment complete!"
          EOF
