name: Deploy PHP App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stash uncommitted changes in q1 folder
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          if [ -d "/var/www/html/q1/.git" ]; then
            cd /var/www/html/q1
            git stash -m "Stashing uncommitted changes in q1" || echo "No uncommitted changes to stash"
          else
            echo "No git repo found in /var/www/html/q1 to stash"
          fi

    - name: Backup q1 folder and upload to S3
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          timestamp=$(date +'%Y-%m-%d_%H-%M-%S')
          backup_path="/home/ec2-user/q1-backup-$timestamp.tar.gz"

          if [ -d "/var/www/html/q1" ]; then
            tar -czf "$backup_path" -C /var/www/html q1
            aws s3 cp "$backup_path" s3://vitwodeploybackup/q1-backups/
          else
            echo "Directory /var/www/html/q1 does not exist, skipping backup"
          fi

    - name: Upload new code to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ec2-user/app"

    - name: Run deployment script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo mkdir -p /var/www/html/q1
          sudo cp -r /home/ec2-user/app/* /var/www/html/q1

          echo "Attempting to restart Apache server..."
          if systemctl list-units --type=service | grep -q httpd; then
            sudo systemctl restart httpd
          elif systemctl list-units --type=service | grep -q apache2; then
            sudo systemctl restart apache2
          elif service --status-all 2>&1 | grep -q httpd; then
            sudo service httpd restart
          elif service --status-all 2>&1 | grep -q apache2; then
            sudo service apache2 restart
          else
            echo "No known Apache service found to restart"
            exit 1
          fi
